---
abstract: 'Serve static files from document root with directory index'
author:
  - 'hayajo <hayajo@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.019
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Directory
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Mojolicious: 3.02
  perl: 5.010001
resources:
  bugtracker: https://github.com/hayajo/Mojolicious-Plugin-Directory/issues
  homepage: https://github.com/hayajo/Mojolicious-Plugin-Directory
  repository: https://github.com/hayajo/Mojolicious-Plugin-Directory.git
version: 0.07
x_contributors:
  - 'hayajo <hayato.imai@gmail.com>'
